# MIT License
# Copyright (c) 2023 Robert1037
# Makefile v1.0
# Last modified: 2023-01-12
all: full once fast min
full:
	gcc ./sha256full.c -o sha256full -O3 -s
once:
	gcc ./sha256once.c -o sha256once -O3 -s
fast:
	gcc ./sha256fast.c -o sha256fast -O3 -s
min:
	gcc ./sha256min.c -o sha256min -Os -s